name: 💡 Propozycja funkcji
description: Zaproponuj nową funkcję lub usprawnienie
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / potrzeba
      description: Jaki problem ma rozwiązać ta funkcja?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proponowane rozwiązanie
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatywy / uwagi
    validations:
      required: false
